version: '2'

services:
    app:
        image: pavelsr/guru-ui
        restart: always
        environment:
        - VIRTUAL_HOST=${VIRTUAL_HOST}
        - VIRTUAL_PORT=${VIRTUAL_PORT}
        - LETSENCRYPT_HOST=${VIRTUAL_HOST}
        - LETSENCRYPT_EMAIL=pavelsr@cpan.org
        command: python3 flask_app.py
        expose:
        - ${VIRTUAL_PORT}
        networks:
        - proxy-tier

networks:
  proxy-tier:
    external:
      name: nginx-proxy
