ab_questions:
  - id: 1
    checkbox_label: безнал
    tts: Скажите, Вам удобно принимать оплату в безналичной форме?
  - id: 2
    checkbox_label: быстро связаться с клиентом
    tts: Скажите, вы сможете связаться с клиентом в течение 5 минут?
  - id: 3
    checkbox_label: расстояние
    tts: Вы далеко находитесь от клиента?
  - id: 4
    checkbox_label: личный транспорт
    tts: У Вас есть личный транспорт?
  - id: 5
    checkbox_label: опыт
    tts: Какой у Вас опыт в выполнении аналогичных заказов?
  - id: 6
    checkbox_label: пунктуальность
    tts: Вы сможете приехать к клиенту ровно в назначенное время?
  - id: 7
    checkbox_label: скидка
    tts: Вы готовы обсуждать условие о скидке?
  - id: 8
    checkbox_label: пунктуальность 2
    tts: Вы готовы выполнить заказ сегодня?
    note: для 2 и 3 группы (ab_groups)
  - id: 9
    checkbox_label: юрлицо (ИП или самозанят.)
    tts: Скажите, вы являетесь ИП или самозанятым?

ab_question_ids_disable:
  - 3
  - 5
  - 7
  - 8

ab_question_label_type: tts

ab_groups:
  - id: 1
    desc: Заказ сегодня (через 4 часа) звонить и предлагать заказ до 14-00 максимальный выход до 18-00
  - id: 2
    desc: Заказ завтра (с утра, в 10.00)
  - id: 2
    desc: Заказ через неделю (в 9.00)

grouptest_phones:
  - 79885851900
  - 79956251900

aimylogic_url: